// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WildBerriesAnalyzer.Data;

namespace WildBerriesAnalyzer.Data.Migrations
{
    [DbContext(typeof(WbDataBase))]
    [Migration("20260802161547_actual_disconts_reference_period_from")]
    partial class actual_disconts_reference_period_from
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("WildBerriesAnalyzer.Domain.Models.DataBase.PriceUpdateJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastError")
                        .HasColumnType("character varying(2000)")
                        .HasMaxLength(2000);

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LockedBy")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<int>("PricesSavedCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ProductsCount")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("LockedAt")
                        .HasName("IX_PriceUpdateJobs_LockedAt");

                    b.HasIndex("Status", "CompletedAt")
                        .HasName("IX_PriceUpdateJobs_Status_CompletedAt");

                    b.ToTable("PriceUpdateJobs");
                });

            modelBuilder.Entity("WildBerriesAnalyzer.Domain.Models.DataBase.WbActualDiscont", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("CurrentPriceCheckTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("DiscontPercent")
                        .HasColumnType("numeric");

                    b.Property<int?>("PriceUpdateJobId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ReferencePrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("ReferencePriceCheckTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ReferencePricePeriodFrom")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ReferencePriceStrategy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("DiscontPercent")
                        .HasName("IX_ActualDisconts_DiscontPercent");

                    b.HasIndex("PriceUpdateJobId");

                    b.HasIndex("ProductId", "ReferencePriceStrategy")
                        .HasName("IX_ActualDisconts_Product_Strategy");

                    b.ToTable("ActualDisconts");
                });

            modelBuilder.Entity("WildBerriesAnalyzer.Domain.Models.DataBase.WbCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("WildBerriesAnalyzer.Domain.Models.DataBase.WbFilter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DiscontMinPercent")
                        .HasColumnType("integer");

                    b.Property<float>("MinRating")
                        .HasColumnType("real");

                    b.Property<int>("MinReviewsCount")
                        .HasColumnType("integer");

                    b.Property<int>("ProductsFilterType")
                        .HasColumnType("integer");

                    b.Property<string[]>("ReferencePriceStrartegies")
                        .HasColumnType("text[]");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Filters");
                });

            modelBuilder.Entity("WildBerriesAnalyzer.Domain.Models.DataBase.WbFilterBag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("FilterId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("FilterId");

                    b.HasIndex("ProductId");

                    b.ToTable("FilterBags");
                });

            modelBuilder.Entity("WildBerriesAnalyzer.Domain.Models.DataBase.WbFilterCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("FilterId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FilterId");

                    b.ToTable("CategoryFilters");
                });

            modelBuilder.Entity("WildBerriesAnalyzer.Domain.Models.DataBase.WbPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CheckTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("PricesHistory");
                });

            modelBuilder.Entity("WildBerriesAnalyzer.Domain.Models.DataBase.WbProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("FeedBacksCount")
                        .HasColumnType("integer");

                    b.Property<long>("IdInMarket")
                        .HasColumnType("bigint");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.Property<double>("ReviewRating")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("IdInMarket")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("WildBerriesAnalyzer.Domain.Models.DataBase.WbUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("AccessToken")
                        .HasColumnType("character varying(2000)")
                        .HasMaxLength(2000);

                    b.Property<int>("BotPlace")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Login")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Password")
                        .HasColumnType("character varying(500)")
                        .HasMaxLength(500);

                    b.Property<string>("RefreshToken")
                        .HasColumnType("character varying(2000)")
                        .HasMaxLength(2000);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("VkId")
                        .HasColumnType("character varying(64)")
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.HasIndex("AccessToken")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("RefreshToken")
                        .IsUnique();

                    b.HasIndex("VkId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WildBerriesAnalyzer.Domain.Models.DataBase.WbActualDiscont", b =>
                {
                    b.HasOne("WildBerriesAnalyzer.Domain.Models.DataBase.PriceUpdateJob", "PriceUpdateJob")
                        .WithMany()
                        .HasForeignKey("PriceUpdateJobId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WildBerriesAnalyzer.Domain.Models.DataBase.WbProduct", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WildBerriesAnalyzer.Domain.Models.DataBase.WbFilter", b =>
                {
                    b.HasOne("WildBerriesAnalyzer.Domain.Models.DataBase.WbUser", "User")
                        .WithOne("Filter")
                        .HasForeignKey("WildBerriesAnalyzer.Domain.Models.DataBase.WbFilter", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WildBerriesAnalyzer.Domain.Models.DataBase.WbFilterBag", b =>
                {
                    b.HasOne("WildBerriesAnalyzer.Domain.Models.DataBase.WbFilter", "Filter")
                        .WithMany("BagProducts")
                        .HasForeignKey("FilterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WildBerriesAnalyzer.Domain.Models.DataBase.WbProduct", "Product")
                        .WithMany("Bags")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WildBerriesAnalyzer.Domain.Models.DataBase.WbFilterCategory", b =>
                {
                    b.HasOne("WildBerriesAnalyzer.Domain.Models.DataBase.WbCategory", "Category")
                        .WithMany("FiltersCategory")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WildBerriesAnalyzer.Domain.Models.DataBase.WbFilter", "Filter")
                        .WithMany("FilterCategories")
                        .HasForeignKey("FilterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WildBerriesAnalyzer.Domain.Models.DataBase.WbPrice", b =>
                {
                    b.HasOne("WildBerriesAnalyzer.Domain.Models.DataBase.WbProduct", "Product")
                        .WithMany("PricesHistory")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WildBerriesAnalyzer.Domain.Models.DataBase.WbProduct", b =>
                {
                    b.HasOne("WildBerriesAnalyzer.Domain.Models.DataBase.WbCategory", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");
                });
#pragma warning restore 612, 618
        }
    }
}
